name: 'Running AQA test'
description: 'Running AQA test'
author: 'Sophia Guo'
inputs:
  jdksource:      # AdoptOpenJDK/install-jdk , github-hosted environment  , upstream
    description: 'github-hosted default or customized'
    default: 'upstream'
  version:              # jdk version
    description: 'testing jdk version (Required when jdksource is github-hosted or install-jdk.)'
    required: false
  build_list:           # test catagory
    description: 
    default: 'openjdk'
  target:              # test
    description: 
    default: '_jdk_custom'
  usePersonalRepo:
    description: 'A boolean value ("true" or "false") on whether the personalRepo should be used.'
    required: false
    default: false
runs:
  using: 'node12'
  main: 'dist/index.js'
