name: "build-test"
on: # rebuild any PRs and main branch changes
  push:

jobs:
  build: # make sure build/ci work properly
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: AQA
      uses: ./
      with: 
        version: '8'
        jdksource:
        build_list: 'openjdk'
        target: '_jdk_custom'
